sonar.projectKey=Muqadas1234_cohort-9-mern-6888-muqadas
sonar.organization=muqadas1234

sonar.sources=backend
sonar.exclusions=**/node_modules/**,**/*.test.js,**/test/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info